version: '3.8'
services:
  node-status:
    image: node:16.13.1
    container_name: node-status
    working_dir: /app
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules:delegated
    ports:
      - ${NEST_LOCAL_PORT}:3000
      - ${NEST_LOCAL_DEBUG_PORT}:9229
    command: sh -c "npm run start:debug"
